### ISSUE TITLE
Initail view

### ISSUE THREAD

**Issue by felipecastro** [LinkedInAttic/LIExposeController#2]
Hi, this code is amazing! i really like to use that in my new project. But i have a question, how do i set the expose view as a initial view when the app lauch (instead a first or another view) like a linkdein app?

tks

**Comment by jmstone617** [comment]
In your AppDelegate, simply call `[exposeController toggleExpose]` after `[self.window makeKeyAndVisible]` in `application:DidFinishLaunchingWithOptions:`

**Comment by felipecastro** [comment]
thanks for answer, that´s works fine!

**Comment by mikelelorz** [comment]
Hi! This solution worked for me but there's one issue. I tried to use [exposeController toggleExpose:NO]; after makeKeyAndVisible but it won't work... I would like to start with the expose zoomed out but without the animation...

**Comment by mikelelorz** [comment]
The problem is that if it's called without animating it, the you can't click on the controllers...
